development:
   adapter: postgresql
   host: localhost
   port: 5432
   database: wiselinks_development
   username: wiselinks
   password: dev
   schema_search_path: public
   encoding: utf8

production:
  adapter: postgresql
  host: localhost
  port: 5432
  database: wiselinks_production
  username: wiselinks
  password: dev
  schema_search_path: public
  encoding: utf8
